### ISSUE TITLE
Errors when upgrading completion and generate endpoints to new engine

### ISSUE THREAD

**Issue by hatgit** [hatgit/forex-gpt#2]
see comment: https://github.com/hatgit/forex-gpt/commit/1adfa1195dc8766f8a9eb53391aecb005c3ae7b2#commitcomment-117933300

**Comment by hatgit** [comment]
resources: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_stream_completions.ipynb

**Comment by pb30** [comment]
the `gpt-*` models need to use `openai.ChatCompletion.create` method, instead of `openai.Completion.create`

```py
completion = openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Hello!"}
  ]
)

print(completion.choices[0].message)
```

https://platform.openai.com/docs/api-reference/chat/create

**Comment by hatgit** [comment]
@pb30 now it is all clear why they weren't working, thank you!

**Comment by hatgit** [comment]
Resolved with commit: https://github.com/hatgit/forex-gpt/commit/6bd9fa60b9e5afc9b0ed41646fba92b6d59c3ff0
